type                = "directrequest"
schemaVersion       = 1
name                = "fetch uint256"
contractAddress     = "ORACLE_ADDRESS"
externalJobID       = "00000000-0000-0000-0000-000000000000"
observationSource = """
    decode_log  [type="ethabidecodelog"
             data="$(jobRun.logData)"
             topics="$(jobRun.logTopics)"
             abi="SomeContractEvent(bytes32 requestID, bytes cborPayload)"]
    decode_cbor [type="cborparse"
                data="$(decode_log.cborPayload)"]

    fetch [type="http" url="$(decode_cbor.url)" method="get"]
    parse [type="jsonparse" path="$(decode_cbor.path)" data="$(fetch)"]
    multiply [type="multiply" input="$(parse)" times="$(decode_cbor.times)"]

    encode_response [type=ethabiencode
                    abi="(uint256 data)"
                    data=<{"data": $(multiply) }>]
    encode_tx       [type=ethabiencode
                    abi="fulfillOracleRequest(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 data)"
                    data=<{
                        "requestId": $(decode_log.requestId),
                        "payment": $(decode_log.payment),
                        "callbackAddress": $(decode_log.callbackAddr),
                        "callbackFunctionId": $(decode_log.callbackFunctionId),
                        "expiration": $(decode_log.cancelExpiration),
                        "data": $(encode_response)
                    }>]
    submit_tx  [type=ethtx to="ORACLE_ADDRESS" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> multiply -> encode_response -> encode_tx -> submit_tx
"""
